server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false           # 关闭自我保护模式（缺省为打开）
    #eviction-interval-timer-in-ms: 5000       # 续期时间，清理失效的服务实例，即扫描失效服务的间隔时间（缺省为60*1000ms
  client:
    registerWithEureka: false
    fetchRegistry: false
    