server:
  port: 8762
spring:
  application:
    name: oms-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
#数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oms_project?useUnicode=true&characterEncoding=GBK
    username: root
    password: 123456
endpoints:
  sensitive: false #敏感端口都可以访问
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5 #心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    metadata-map:
      company-name: crazyit
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    #instance-info-replication-interval-seconds: 10 ＃默认30秒 当服务状态改变，多久在服务注册列表相应并改变状态，健康管理
#logging:
 # level:
  #  com.netflix: DEBUG
#rabbitmq:
#  host: localhost
#  port: 5672
#  username: guest
#  password: guest
